# Save this as .github/workflows/keep-alive.yml in your repository

name: Keep Streamlit App Alive

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          echo "Pinging app at $(date)"
          curl -f -s -o /dev/null https://talent-search.streamlit.app || echo "Ping failed"
          echo "Ping completed"